// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgxsgvveuqfsnafqulrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZneHNndnZldXFmc25hZnF1bHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODE5MjMsImV4cCI6MjA2NzE1NzkyM30.wbo5Wecd-itXViqnLXpIdicKz1Ca402ef4pDWmvGjWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});